# Generated by Django 5.1.15 on 2026-08-01 19:35

import apps.common.storage
import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('category', models.CharField(db_index=True, default='lifestyle', max_length=40)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'profiles_interest',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MatchPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('interested_in', models.JSONField(blank=True, default=list, help_text='List of Gender values; empty means everyone.')),
                ('min_age', models.PositiveSmallIntegerField(default=18)),
                ('max_age', models.PositiveSmallIntegerField(default=45)),
                ('max_distance_km', models.PositiveSmallIntegerField(default=100)),
                ('preferred_relationship_goals', models.JSONField(blank=True, default=list)),
                ('preferred_education_levels', models.JSONField(blank=True, default=list)),
                ('preferred_languages', models.JSONField(blank=True, default=list)),
                ('preferred_religion', models.CharField(blank=True, max_length=60)),
                ('smoking_preference', models.CharField(blank=True, choices=[('never', 'Never'), ('socially', 'Socially'), ('regularly', 'Regularly'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('drinking_preference', models.CharField(blank=True, choices=[('never', 'Never'), ('socially', 'Socially'), ('regularly', 'Regularly'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('children_preference', models.CharField(blank=True, choices=[('none', "Don't have children"), ('have', 'Have children'), ('want', 'Want children'), ('dont_want', "Don't want children"), ('open', 'Open to children')], max_length=20)),
                ('verified_only', models.BooleanField(default=False)),
                ('with_photos_only', models.BooleanField(default=True)),
                ('show_me_globally', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'profiles_match_preference',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('headline', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('gender', models.CharField(blank=True, choices=[('woman', 'Woman'), ('man', 'Man'), ('non_binary', 'Non-binary'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], db_index=True, max_length=20)),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High school'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's degree"), ('master', "Master's degree"), ('doctorate', 'Doctorate'), ('other', 'Other')], db_index=True, max_length=20)),
                ('school', models.CharField(blank=True, max_length=150)),
                ('smoking', models.CharField(blank=True, choices=[('never', 'Never'), ('socially', 'Socially'), ('regularly', 'Regularly'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('drinking', models.CharField(blank=True, choices=[('never', 'Never'), ('socially', 'Socially'), ('regularly', 'Regularly'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('exercise', models.CharField(blank=True, choices=[('never', 'Never'), ('socially', 'Socially'), ('regularly', 'Regularly'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('children', models.CharField(blank=True, choices=[('none', "Don't have children"), ('have', 'Have children'), ('want', 'Want children'), ('dont_want', "Don't want children"), ('open', 'Open to children')], max_length=20)),
                ('religion', models.CharField(blank=True, max_length=60)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('relationship_goal', models.CharField(blank=True, choices=[('long_term', 'Long-term relationship'), ('short_term', 'Something casual'), ('friendship', 'New friends'), ('marriage', 'Marriage'), ('unsure', 'Still figuring it out')], db_index=True, max_length=20)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, db_index=True, max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.common.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.common.validators.validate_longitude])),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('completion_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('photo_count', models.PositiveSmallIntegerField(default=0)),
                ('primary_photo_url', models.CharField(blank=True, max_length=255)),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text="Off means the profile never appears in anyone's feed.")),
                ('is_boosted_until', models.DateTimeField(blank=True, null=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.interest')),
            ],
            options={
                'db_table': 'profiles_profile',
                'indexes': [models.Index(fields=['gender', 'is_visible'], name='profiles_pr_gender_6e7247_idx'), models.Index(fields=['latitude', 'longitude'], name='profiles_pr_latitud_6b6a14_idx'), models.Index(fields=['country', 'city'], name='profiles_pr_country_d83f94_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=apps.common.storage.profile_photo_path, validators=[apps.common.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('position', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12)),
                ('moderation_note', models.CharField(blank=True, max_length=255)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_photo',
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['user', 'position'], name='profiles_ph_user_id_7698cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='discovery', max_length=30)),
                ('viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_profile_view',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['viewed', '-created_at'], name='profiles_pr_viewed__1bc047_idx'), models.Index(fields=['viewer', 'viewed'], name='profiles_pr_viewer__1c9c46_idx')],
            },
        ),
    ]
