# Generated by Django 5.1.15 on 2026-08-01 19:35

import apps.accounts.managers
import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, validators=[apps.common.validators.validate_phone])),
                ('username', models.CharField(db_index=True, max_length=30, unique=True, validators=[apps.common.validators.validate_username])),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('support', 'Support agent'), ('analyst', 'Analyst'), ('admin', 'Administrator')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned'), ('deactivated', 'Deactivated by user')], db_index=True, default='pending', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_photo_verified', models.BooleanField(default=False)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('verification_level', models.PositiveSmallIntegerField(choices=[(0, 'Unverified'), (1, 'Email verified'), (2, 'Phone verified'), (3, 'Photo verified'), (4, 'Identity verified')], default=0)),
                ('is_mfa_enabled', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('has_completed_onboarding', models.BooleanField(default=False)),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1)),
                ('last_active_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('language', models.CharField(default='en', max_length=10)),
                ('theme', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('notify_on_match', models.BooleanField(default=True)),
                ('notify_on_message', models.BooleanField(default=True)),
                ('notify_on_like', models.BooleanField(default=True)),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_distance', models.BooleanField(default=True)),
                ('show_age', models.BooleanField(default=True)),
                ('show_last_active', models.BooleanField(default=True)),
                ('incognito_mode', models.BooleanField(default=False)),
                ('read_receipts_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'User settings',
                'db_table': 'accounts_user_settings',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('push_token', models.CharField(blank=True, max_length=255)),
                ('is_trusted', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_device',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'is_active'], name='accounts_us_status_71331c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-last_active_at'], name='accounts_us_last_ac_0b980a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'fingerprint')},
        ),
    ]
