services:
  - type: web
    name: dateapp
    runtime: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health/
    dockerCommand: sh docker/start-web.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DB_ENGINE
        value: postgres
      - key: DB_NAME
        fromDatabase:
          name: dateapp-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: dateapp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dateapp-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: dateapp-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dateapp-db
          property: port

databases:
  - name: dateapp-db
    plan: free
    databaseName: dateapp
    user: dateapp
