# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPReputation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('score', models.SmallIntegerField(default=100, help_text='0 (hostile) to 100 (clean).')),
                ('failed_logins', models.PositiveIntegerField(default=0)),
                ('blocked_requests', models.PositiveIntegerField(default=0)),
                ('accounts_seen', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=400)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'security_ip_reputation',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitBreach',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(db_index=True, max_length=60)),
                ('identifier', models.CharField(db_index=True, max_length=191)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('limit', models.PositiveIntegerField(default=0)),
                ('window_seconds', models.PositiveIntegerField(default=0)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'security_rate_limit_breach',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('new_device', 'Login from a new device'), ('new_location', 'Login from a new location'), ('impossible_travel', 'Impossible travel'), ('credential_stuffing', 'Credential stuffing pattern'), ('brute_force', 'Brute force attempt'), ('rate_limit', 'Rate limit exceeded'), ('suspicious_ip', 'Request from a flagged IP'), ('session_hijack', 'Possible session hijack'), ('mass_action', 'Unusual volume of actions'), ('privilege_escalation', 'Privilege escalation attempt')], db_index=True, max_length=24)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('description', models.CharField(max_length=400)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='security_ev_user_id_cc6e36_idx'), models.Index(fields=['severity', 'is_resolved'], name='security_ev_severit_a41476_idx')],
            },
        ),
    ]
