# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.UUIDField(db_index=True, help_text="UUID of a record owned by the 'accounts' service.", verbose_name='accounts reference')),
                ('set_name', models.CharField(choices=[('top_picks', 'Top picks'), ('nearby', 'People near you'), ('most_compatible', 'Most compatible'), ('recently_active', 'Recently active'), ('new_members', 'New on Zynora')], db_index=True, default='top_picks', max_length=20)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=140)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('was_shown', models.BooleanField(default=False)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('was_acted_on', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_recommendation',
                'ordering': ['set_name', 'rank'],
                'indexes': [models.Index(fields=['user', 'set_name', 'rank'], name='recommendat_user_id_455674_idx')],
                'unique_together': {('user', 'candidate_id', 'set_name')},
            },
        ),
    ]
