# Generated by Django 5.1.15 on 2026-08-01 19:35

import apps.common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationBadge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification_badge', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('selfie_verified_at', models.DateTimeField(blank=True, null=True)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verification_badge',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email', 'Email address'), ('phone', 'Phone number'), ('selfie', 'Selfie / photo verification'), ('government_id', 'Government ID')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10)),
                ('challenge_pose', models.CharField(blank=True, max_length=60)),
                ('document', models.ImageField(blank=True, null=True, upload_to=apps.common.storage.verification_document_path)),
                ('document_number_hint', models.CharField(blank=True, help_text='Last characters only — never the full number.', max_length=8)),
                ('target_value', models.CharField(blank=True, help_text='Phone or email being verified.', max_length=191)),
                ('auto_confidence', models.PositiveSmallIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'kind', 'status'], name='verificatio_user_id_609975_idx'), models.Index(fields=['status', '-created_at'], name='verificatio_status_eddf4c_idx')],
            },
        ),
    ]
