# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(db_index=True, max_length=80, unique=True)),
                ('category', models.CharField(default='abuse', max_length=40)),
                ('action', models.CharField(choices=[('flag', 'Flag for review'), ('mask', 'Mask the term'), ('block', 'Block the content')], default='flag', max_length=8)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_regex', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'moderation_banned_term',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trust_score', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.SmallIntegerField(default=100, help_text='0 (untrusted) to 100 (fully trusted).')),
                ('flags_received', models.PositiveIntegerField(default=0)),
                ('reports_received', models.PositiveIntegerField(default=0)),
                ('content_rejected', models.PositiveIntegerField(default=0)),
                ('is_shadow_banned', models.BooleanField(db_index=True, default=False)),
                ('shadow_banned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'moderation_trust_score',
            },
        ),
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(db_index=True, help_text="UUID of a record owned by the 'accounts' service.", verbose_name='accounts reference')),
                ('object_type', models.CharField(choices=[('profile_photo', 'Profile photo'), ('profile_text', 'Profile text'), ('message', 'Chat message'), ('verification_photo', 'Verification photo')], db_index=True, max_length=24)),
                ('object_id', models.UUIDField(db_index=True)),
                ('content_snapshot', models.TextField(blank=True)),
                ('content_url', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('auto_approved', 'Auto-approved'), ('auto_rejected', 'Auto-rejected'), ('approved', 'Approved by moderator'), ('rejected', 'Rejected by moderator'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=400)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_case',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='moderation__status_03ddf2_idx'), models.Index(fields=['object_type', 'object_id'], name='moderation__object__52e236_idx')],
            },
        ),
    ]
