# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipeQuota',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='swipe_quota', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('likes_used', models.PositiveSmallIntegerField(default=0)),
                ('super_likes_used', models.PositiveSmallIntegerField(default=0)),
                ('rewinds_used', models.PositiveSmallIntegerField(default=0)),
                ('reset_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'likes_swipe_quota',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('like', 'Like'), ('super_like', 'Super like'), ('pass', 'Pass')], db_index=True, default='like', max_length=12)),
                ('message', models.CharField(blank=True, help_text='Optional note attached to a super like.', max_length=200)),
                ('source', models.CharField(default='discovery', max_length=30)),
                ('score_at_swipe', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_rewound', models.BooleanField(db_index=True, default=False)),
                ('seen_by_receiver', models.BooleanField(db_index=True, default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes_like',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', 'kind', 'seen_by_receiver'], name='likes_like_receive_022d18_idx'), models.Index(fields=['sender', '-created_at'], name='likes_like_sender__213405_idx')],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
