# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='TZS', max_length=3)),
                ('duration_days', models.PositiveSmallIntegerField(default=30)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('entitlements', models.JSONField(blank=True, default=list, help_text='List of Entitlement values.')),
                ('daily_likes', models.PositiveSmallIntegerField(blank=True, default=20, null=True)),
                ('daily_super_likes', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('daily_rewinds', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('daily_messages', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('monthly_boosts', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False, help_text='The plan every new member starts on.')),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('badge_color', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'subscriptions_plan',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off'), ('free_days', 'Free days')], default='percent', max_length=12)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveSmallIntegerField(default=1)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to_plans', models.ManyToManyField(blank=True, related_name='coupons', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'subscriptions_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'In trial'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('auto_renew', models.BooleanField(default=True)),
                ('renewal_count', models.PositiveSmallIntegerField(default=0)),
                ('payment_id', models.UUIDField(blank=True, db_index=True, help_text="UUID of a record owned by the 'payments' service.", null=True, verbose_name='payments reference')),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='TZS', max_length=3)),
                ('boosts_remaining', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_subscription',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='subscriptions.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscriptions_coupon_redemption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'expires_at'], name='subscriptio_status_067d55_idx'),
        ),
    ]
