# Generated by Django 5.1.15 on 2026-08-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_paid_plans_see_who_likes_you'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
