# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('flutterwave', 'Flutterwave'), ('pesapal', 'Pesapal'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('tigo_pesa', 'Mixx by Yas (Tigo Pesa)'), ('halopesa', 'HaloPesa'), ('manual', 'Manual / offline')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], db_index=True, default='pending', max_length=20)),
                ('purpose', models.CharField(choices=[('subscription', 'New subscription'), ('subscription_renewal', 'Subscription renewal'), ('boost', 'Profile boost'), ('super_like_pack', 'Super like pack'), ('other', 'Other')], default='subscription', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='TZS', max_length=3)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=191)),
                ('checkout_url', models.URLField(blank=True)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='TZS', max_length=3)),
                ('billing_name', models.CharField(blank=True, max_length=120)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_invoice',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=191)),
                ('is_complete', models.BooleanField(default=False)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_issued', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_refund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('flutterwave', 'Flutterwave'), ('pesapal', 'Pesapal'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('tigo_pesa', 'Mixx by Yas (Tigo Pesa)'), ('halopesa', 'HaloPesa'), ('manual', 'Manual / offline')], max_length=20)),
                ('token', models.CharField(max_length=191)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('brand', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_saved_method',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('flutterwave', 'Flutterwave'), ('pesapal', 'Pesapal'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('tigo_pesa', 'Mixx by Yas (Tigo Pesa)'), ('halopesa', 'HaloPesa'), ('manual', 'Manual / offline')], db_index=True, max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=191)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signature_verified', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'db_table': 'payments_webhook_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'external_id'], name='payments_we_provide_0bb177_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'provider'], name='payments_pa_status_eb2eec_idx'),
        ),
    ]
