# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidates_considered', models.PositiveIntegerField(default=0)),
                ('candidates_scored', models.PositiveIntegerField(default=0)),
                ('filtered_out', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('top_score', models.PositiveSmallIntegerField(default=0)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilityScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(db_index=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_received', to=settings.AUTH_USER_MODEL)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_computed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_compatibility_score',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['seeker', '-score'], name='matching_co_seeker__353763_idx')],
                'unique_together': {('seeker', 'candidate')},
            },
        ),
    ]
