# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='onboarding', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_step', models.PositiveSmallIntegerField(choices=[(1, 'Welcome'), (2, 'About you'), (3, 'Photos'), (4, 'Interests'), (5, "What you're looking for"), (6, 'Location'), (7, 'Finished')], default=1)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_steps', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Onboarding progress',
                'db_table': 'onboarding_progress',
            },
        ),
    ]
