# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, max_length=191)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('account', 'Account'), ('profile', 'Profile'), ('engagement', 'Engagement'), ('messaging', 'Messaging'), ('billing', 'Billing'), ('safety', 'Trust and safety'), ('admin', 'Administration'), ('security', 'Security'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_sensitive', models.BooleanField(db_index=True, default=False, help_text='Entries staff should not browse casually.')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_log_actor_i_91cd96_idx'), models.Index(fields=['category', '-created_at'], name='audit_log_categor_ba4a92_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_log_object__8ccc11_idx')],
            },
        ),
    ]
