# Generated by Django 5.1.15 on 2026-08-01 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('signups', models.PositiveIntegerField(default=0)),
                ('verified_email', models.PositiveIntegerField(default=0)),
                ('completed_onboarding', models.PositiveIntegerField(default=0)),
                ('sent_first_like', models.PositiveIntegerField(default=0)),
                ('got_first_match', models.PositiveIntegerField(default=0)),
                ('sent_first_message', models.PositiveIntegerField(default=0)),
                ('subscribed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_funnel_snapshot',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('metric', models.CharField(db_index=True, max_length=60)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('dimension', models.CharField(blank=True, help_text='Optional breakdown key, e.g. a plan code or provider.', max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'analytics_daily_metric',
                'ordering': ['-date', 'metric'],
                'indexes': [models.Index(fields=['metric', '-date'], name='analytics_d_metric_a601d9_idx')],
                'unique_together': {('date', 'metric', 'dimension')},
            },
        ),
    ]
