# Generated by Django 5.1.15 on 2026-08-01 19:35

import apps.common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('account', 'Account'), ('billing', 'Billing'), ('safety', 'Safety'), ('technical', 'Technical'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', max_length=12)),
                ('subject', models.CharField(max_length=140)),
                ('message', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting', 'Waiting on member'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('is_priority', models.BooleanField(default=False)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_assigned', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_support_ticket',
                'ordering': ['-is_priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('from_report', models.BooleanField(default=False)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_block',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker'], name='reports_blo_blocker_56724e_idx'), models.Index(fields=['blocked'], name='reports_blo_blocked_710e77_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('fake_profile', 'Fake profile or catfish'), ('harassment', 'Harassment or abuse'), ('inappropriate_photos', 'Inappropriate photos'), ('scam', 'Scam or asking for money'), ('underage', 'Appears to be under 18'), ('spam', 'Spam or advertising'), ('off_platform', 'Pushing to another app'), ('hate_speech', 'Hate speech'), ('threat', 'Threats or violence'), ('other', 'Something else')], db_index=True, max_length=24)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to=apps.common.storage.report_evidence_path)),
                ('context_type', models.CharField(blank=True, max_length=40)),
                ('context_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Under review'), ('actioned', 'Action taken'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=12)),
                ('outcome', models.CharField(choices=[('none', 'No action'), ('warning', 'Warning issued'), ('content_removed', 'Content removed'), ('shadow_banned', 'Shadow banned'), ('suspended', 'Account suspended'), ('banned', 'Account banned')], default='none', max_length=16)),
                ('is_urgent', models.BooleanField(db_index=True, default=False)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_note', models.TextField(blank=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_report',
                'ordering': ['-is_urgent', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='reports_rep_status_7dd5e5_idx'), models.Index(fields=['reported', 'status'], name='reports_rep_reporte_0f9611_idx')],
            },
        ),
    ]
