# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFASecret',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mfa', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('secret', models.CharField(max_length=64)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_codes', models.JSONField(blank=True, default=list)),
                ('last_used_counter', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'MFA secret',
                'db_table': 'auth_mfa_secret',
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('jti', models.CharField(blank=True, db_index=True, help_text='JWT refresh token id, when the session is API-based.', max_length=64)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_active_session',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('bad_credentials', 'Wrong password'), ('unknown_user', 'No such account'), ('locked', 'Account locked'), ('banned', 'Account banned'), ('mfa_required', 'MFA challenge issued'), ('mfa_failed', 'MFA code rejected'), ('rate_limited', 'Rate limited')], db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_login_attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', '-created_at'], name='auth_login__identif_e62553_idx'), models.Index(fields=['ip_address', '-created_at'], name='auth_login__ip_addr_af3a70_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email verification'), ('password_reset', 'Password reset'), ('email_change', 'Email change'), ('phone_otp', 'Phone OTP'), ('mfa_challenge', 'MFA challenge'), ('device_confirmation', 'New device confirmation')], db_index=True, max_length=32)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_security_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', 'token_hash'], name='auth_securi_purpose_afdb93_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple'), ('x', 'X')], max_length=20)),
                ('provider_uid', models.CharField(db_index=True, max_length=191)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_social_account',
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
    ]
