# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('match', 'New match'), ('like', 'Someone liked you'), ('super_like', 'Super like'), ('message', 'New message'), ('profile_view', 'Profile view'), ('verification', 'Verification update'), ('subscription', 'Subscription update'), ('payment', 'Payment update'), ('security', 'Security alert'), ('moderation', 'Moderation notice'), ('system', 'System')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, help_text="UUID of a record owned by the 'accounts' service.", null=True, verbose_name='accounts reference')),
                ('actor_name', models.CharField(blank=True, max_length=80)),
                ('actor_avatar_url', models.CharField(blank=True, max_length=255)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=40)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed by preferences')], db_index=True, default='pending', max_length=12)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('template', models.CharField(blank=True, max_length=60)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('error', models.CharField(blank=True, max_length=400)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'db_table': 'notifications_delivery_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'kind'], name='notificatio_user_id_7b7033_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_f79488_idx'),
        ),
    ]
