# Generated by Django 5.1.15 on 2026-08-02 08:46

from django.conf import settings
from django.db import migrations, models

#: Mirrors INBOX_KINDS in services.py. Duplicated on purpose — a migration must
#: keep working when that module changes.
INBOX_KINDS = ["like", "super_like", "match", "message"]


def backfill_inbox_flag(apps, schema_editor):
    """Existing rows default to in_inbox=True; clear it for operational kinds.

    Nothing is deleted — support and the member's own pages still need the
    history. It simply stops flooding the inbox and the unread badge.
    """
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.exclude(kind__in=INBOX_KINDS).update(in_inbox=False)


def restore_all(apps, schema_editor):
    apps.get_model("notifications", "Notification").objects.update(in_inbox=True)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_icon_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_f2ad08_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='in_inbox',
            field=models.BooleanField(db_index=True, default=True, help_text="Shown in the member's notification inbox. Operational records are retained but excluded — see INBOX_KINDS."),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'in_inbox', 'is_read', '-created_at'], name='notificatio_user_id_bd84bf_idx'),
        ),
        migrations.RunPython(backfill_inbox_flag, restore_all),
    ]
