# Generated by Django 5.1.15 on 2026-08-01 19:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unmatched', 'Unmatched'), ('blocked', 'Blocked'), ('expired', 'Expired')], db_index=True, default='active', max_length=12)),
                ('origin', models.CharField(choices=[('mutual_like', 'Mutual like'), ('super_like', 'Super like'), ('admin', 'Created by admin')], default='mutual_like', max_length=16)),
                ('compatibility_score', models.PositiveSmallIntegerField(default=0)),
                ('matched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_interaction_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=140)),
                ('has_conversation', models.BooleanField(default=False)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_ended', to=settings.AUTH_USER_MODEL)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches_match',
                'ordering': ['-matched_at'],
                'indexes': [models.Index(fields=['user_low', 'status'], name='matches_mat_user_lo_814309_idx'), models.Index(fields=['user_high', 'status'], name='matches_mat_user_hi_902799_idx'), models.Index(fields=['status', '-last_interaction_at'], name='matches_mat_status_4461c5_idx')],
                'unique_together': {('user_low', 'user_high')},
            },
        ),
    ]
