# Generated by Django 5.1.15 on 2026-08-09 09:25

import apps.common.storage
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.storage.chat_document_path, validators=[apps.common.validators.validate_document_file]),
        ),
        migrations.AddField(
            model_name='message',
            name='document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.storage.chat_video_path, validators=[apps.common.validators.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice note'), ('video', 'Video'), ('document', 'Document'), ('gif', 'GIF'), ('system', 'System')], default='text', max_length=10),
        ),
    ]
